import {
  Product,
  Project,
  RFQ,
  Quote,
  Order,
  Document,
  Conversation,
  Message,
  Notification,
  Organization,
} from '@wuchan/contracts';

export const MOCK_ORGANIZATION: Organization = {
  id: 'org_horizon_resorts',
  name: 'Horizon International Eco Resorts LLC',
  taxId: 'US-984729104-EIN',
  preferredCurrency: 'USD',
  destinationPort: 'Port of Los Angeles (USLAX)',
  country: 'United States',
  address: '100 Ocean Boulevard, Suite 400, Santa Monica, CA 90401',
  contactEmail: 'procurement@horizonresorts.com',
  members: [
    {
      id: 'usr_lead_1',
      email: 'alex.morgan@horizonresorts.com',
      fullName: 'Alex Morgan',
      role: 'PROCUREMENT_LEAD',
    },
    {
      id: 'usr_arch_1',
      email: 'sara.chen@horizonresorts.com',
      fullName: 'Sara Chen',
      role: 'ARCHITECT',
    },
    {
      id: 'usr_fin_1',
      email: 'david.vance@horizonresorts.com',
      fullName: 'David Vance',
      role: 'FINANCE_OFFICER',
    },
  ],
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_space_pod_x7',
    sku: 'WCH-POD-X7',
    name: {
      en: 'Space Capsule Luxury Glamping Pod X7',
      zh: '太空舱豪华露营胶囊 X7',
    },
    tagline: {
      en: 'Futuristic 38m² modular capsule with panoramic curved skylight',
      zh: '38平米未来感模块化太空舱，配备全景弧形天窗',
    },
    description: {
      en: 'Aerospace-grade galvanized steel framework with fluorocarbon aluminum alloy shell, polyurethane thermal insulation, and integrated smart control system.',
      zh: '航天级镀锌钢结构框架，搭配氟碳铝合金外壳、聚氨酯保温层及智能控制系统。',
    },
    structureType: 'LUXURY_POD',
    primaryUsage: ['HOSPITALITY', 'RESIDENTIAL'],
    basePriceUsd: { amountCents: Math.round(48500 * 100), currency: 'USD' },
    baseLeadTimeDays: 35,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    floorPlanImages: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
    ],
    physicalProfile: {
      lengthMm: 11500,
      widthMm: 3300,
      heightMm: 3200,
      floorAreaSqm: 37.95,
      weightKg: 8500,
      shippingVolumeCbm: 121.4,
      containerTypeNeeded: '40ft_HC',
      containersRequired: 1,
    },
    performanceSpecs: {
      windResistanceKmh: 180,
      snowLoadKnSqm: 2.5,
      seismicRating: 'Grade 8 (0.3g)',
      fireRating: 'Class A1 Non-combustible',
      thermalInsulationRValue: 28,
      soundproofDb: 42,
      lifespanYears: 50,
      regionalCertifications: ['US_IRC', 'EU_CE', 'AU_AS_NZS'],
    },
    optionGroups: [
      {
        id: 'grp_insulation',
        code: 'INSULATION_SPEC',
        name: { en: 'Thermal Insulation Level', zh: '保温隔热等级' },
        isRequired: true,
        values: [
          {
            id: 'val_ins_std',
            name: { en: 'Standard PU 100mm (R-24)', zh: '标准聚氨酯100mm (R-24)' },
            priceDeltaUsd: { amountCents: Math.round(0 * 100), currency: 'USD' },
            weightDeltaKg: 0,
            cbmDelta: 0,
            leadTimeDeltaDays: 0,
            isDefault: true,
          },
          {
            id: 'val_ins_extreme',
            name: { en: 'Extreme Cold Polyisocyanurate 150mm (R-38)', zh: '极寒聚异氰脲酸酯150mm (R-38)' },
            priceDeltaUsd: { amountCents: Math.round(3200 * 100), currency: 'USD' },
            weightDeltaKg: 250,
            cbmDelta: 0,
            leadTimeDeltaDays: 3,
          },
        ],
      },
    ],
    standardBom: [
      {
        id: 'bom_steel_frame',
        name: { en: 'Main Structural Galvanized Steel Frame', zh: '主结构热镀锌钢框架' },
        category: 'STRUCTURAL_STEEL',
        specifications: 'Q355B Galvanized Steel, 275g/m² zinc coating',
        quantity: 1,
        unit: 'set',
        unitCostUsd: { amountCents: Math.round(18500 * 100), currency: 'USD' },
      },
    ],
  },
  {
    id: 'prod_expandable_v2',
    sku: 'WCH-EXP-20',
    name: {
      en: '20ft Foldable Expandable Container Home V2',
      zh: '20英尺双翼折叠展开式集装箱房 V2',
    },
    tagline: {
      en: 'Rapid deployment 37m² 2-bedroom modular home expands in 15 minutes',
      zh: '快速部署37平米两居室模块化住宅，15分钟展开成型',
    },
    description: {
      en: 'Heavy-duty hydraulic/manual expandable wings with pre-installed kitchen, bathroom, electrical wiring, and plumbing.',
      zh: '重型折叠机构，预装厨房、精装卫生间、水电管线。',
    },
    structureType: 'EXPANDABLE_CONTAINER',
    primaryUsage: ['RESIDENTIAL', 'EMERGENCY_HOUSING', 'COMMERCIAL'],
    basePriceUsd: { amountCents: Math.round(19800 * 100), currency: 'USD' },
    baseLeadTimeDays: 20,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    ],
    floorPlanImages: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    ],
    physicalProfile: {
      lengthMm: 5900,
      widthMm: 6300,
      heightMm: 2480,
      floorAreaSqm: 37.17,
      weightKg: 2800,
      shippingVolumeCbm: 14.8,
      containerTypeNeeded: '40ft_HC',
      containersRequired: 0.5,
    },
    performanceSpecs: {
      windResistanceKmh: 140,
      snowLoadKnSqm: 1.8,
      seismicRating: 'Grade 7',
      fireRating: 'Class B1',
      thermalInsulationRValue: 20,
      soundproofDb: 35,
      lifespanYears: 30,
      regionalCertifications: ['US_IRC', 'EU_CE', 'AU_AS_NZS'],
    },
    optionGroups: [],
    standardBom: [],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_big_sur_resort',
    organizationId: 'org_horizon_resorts',
    code: 'PRJ-2025-001',
    name: 'Big Sur Coastline Eco Resort Phase 1',
    description: '12 Luxury Space Pods and 1 Central Modular Office.',
    site: {
      id: 'site_big_sur',
      name: 'Big Sur Highway 1 Parcel B',
      locationAddress: '48200 Highway 1, Big Sur, CA 93920',
      country: 'United States',
      destinationPort: 'Port of Los Angeles (USLAX)',
      soilBearingCapacityKpa: 180,
      applicableBuildingCode: 'US California Title 24 / Monterey County IBC 2021',
      siteSurveyCompleted: true,
    },
    targetDeliveryDate: '2025-06-15',
    budgetUsd: { amountCents: Math.round(750000 * 100), currency: 'USD' },
    status: 'ACTIVE',
    rfqIds: ['rfq_2025_001'],
    orderIds: ['ord_2025_9912'],
    createdAt: '2025-01-10T08:00:00Z',
  },
];

export const MOCK_RFQS: RFQ[] = [
  {
    id: 'rfq_2025_001',
    rfqNumber: 'RFQ-2025-0089',
    projectId: 'proj_big_sur_resort',
    projectName: 'Big Sur Coastline Eco Resort Phase 1',
    organizationId: 'org_horizon_resorts',
    status: 'QUOTED',
    items: [
      {
        id: 'rfq_item_1',
        productId: 'prod_space_pod_x7',
        productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
        quantity: 12,
        configuration: {
          id: 'cfg_pod_12units',
          productId: 'prod_space_pod_x7',
          productSku: 'WCH-POD-X7',
          productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
          selectedOptions: [],
          calculatedPriceUsd: { amountCents: Math.round(61200 * 100), currency: 'USD' },
          calculatedWeightKg: 9130,
          calculatedCbm: 122.2,
          calculatedLeadTimeDays: 43,
          containersRequired: 1,
          createdAt: '2025-01-12T09:15:00Z',
        },
      },
    ],
    destinationPort: 'Port of Los Angeles (USLAX)',
    incotermsRequested: 'DDP',
    requestedDeliveryDate: '2025-06-15',
    attachments: [],
    quotesGeneratedIds: ['qte_2025_8819'],
    createdAt: '2025-01-12T09:30:00Z',
    updatedAt: '2025-01-14T14:00:00Z',
  },
];

export const MOCK_QUOTES: Quote[] = [
  {
    id: 'qte_2025_8819',
    quoteNumber: 'QTE-2025-8819',
    rfqId: 'rfq_2025_001',
    rfqNumber: 'RFQ-2025-0089',
    projectId: 'proj_big_sur_resort',
    projectName: 'Big Sur Coastline Eco Resort Phase 1',
    organizationId: 'org_horizon_resorts',
    status: 'ACCEPTED',
    acceptedAt: '2025-01-20T16:45:00Z',
    acceptedByUserId: 'usr_lead_1',
    purchaseOrderRef: 'PO-HORIZON-2025-004',
    currentVersion: {
      versionNumber: 2,
      issuedAt: '2025-01-18T10:00:00Z',
      validUntil: '2025-02-18T23:59:59Z',
      lineItems: [
        {
          id: 'qitem_1',
          productId: 'prod_space_pod_x7',
          productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
          configurationSnapshot: {
            id: 'cfg_pod_12units',
            productId: 'prod_space_pod_x7',
            productSku: 'WCH-POD-X7',
            productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
            selectedOptions: [],
            calculatedPriceUsd: { amountCents: Math.round(61200 * 100), currency: 'USD' },
            calculatedWeightKg: 9130,
            calculatedCbm: 122.2,
            calculatedLeadTimeDays: 43,
            containersRequired: 1,
            createdAt: '2025-01-12T09:15:00Z',
          },
          quantity: 12,
          unitPriceUsd: { amountCents: Math.round(59800 * 100), currency: 'USD' },
          totalPriceUsd: { amountCents: Math.round(717600 * 100), currency: 'USD' },
          leadTimeDays: 40,
        },
      ],
      subtotalUsd: { amountCents: Math.round(717600 * 100), currency: 'USD' },
      seaFreightEstimateUsd: { amountCents: Math.round(48000 * 100), currency: 'USD' },
      customsInsuranceEstimateUsd: { amountCents: Math.round(14200 * 100), currency: 'USD' },
      discountUsd: { amountCents: Math.round(16800 * 100), currency: 'USD' },
      totalUsd: { amountCents: Math.round(763000 * 100), currency: 'USD' },
      incoterms: 'DDP',
      paymentTermsNote: '30% Deposit upon contract signing; 40% Mid-production completion; 30% Pre-shipment dispatch.',
      validityDays: 30,
      sellerNotes: 'Volume discount applied.',
      changesSummaryFromPrevious: 'Applied $16,800 volume discount and reduced sea freight by $2,400.',
    },
    versionHistory: [
      {
        versionNumber: 1,
        issuedAt: '2025-01-14T14:00:00Z',
        validUntil: '2025-02-14T23:59:59Z',
        lineItems: [
          {
            id: 'qitem_1_v1',
            productId: 'prod_space_pod_x7',
            productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
            configurationSnapshot: {
              id: 'cfg_pod_12units',
              productId: 'prod_space_pod_x7',
              productSku: 'WCH-POD-X7',
              productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
              selectedOptions: [],
              calculatedPriceUsd: { amountCents: Math.round(61200 * 100), currency: 'USD' },
              calculatedWeightKg: 9130,
              calculatedCbm: 122.2,
              calculatedLeadTimeDays: 43,
              containersRequired: 1,
              createdAt: '2025-01-12T09:15:00Z',
            },
            quantity: 12,
            unitPriceUsd: { amountCents: Math.round(61200 * 100), currency: 'USD' },
            totalPriceUsd: { amountCents: Math.round(734400 * 100), currency: 'USD' },
            leadTimeDays: 43,
          },
        ],
        subtotalUsd: { amountCents: Math.round(734400 * 100), currency: 'USD' },
        seaFreightEstimateUsd: { amountCents: Math.round(50400 * 100), currency: 'USD' },
        customsInsuranceEstimateUsd: { amountCents: Math.round(15000 * 100), currency: 'USD' },
        discountUsd: { amountCents: Math.round(0 * 100), currency: 'USD' },
        totalUsd: { amountCents: Math.round(799800 * 100), currency: 'USD' },
        incoterms: 'DDP',
        paymentTermsNote: '30% Deposit; 40% Mid-production; 30% Pre-shipment.',
        validityDays: 30,
      },
      {
        versionNumber: 2,
        issuedAt: '2025-01-18T10:00:00Z',
        validUntil: '2025-02-18T23:59:59Z',
        lineItems: [
          {
            id: 'qitem_1',
            productId: 'prod_space_pod_x7',
            productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
            configurationSnapshot: {
              id: 'cfg_pod_12units',
              productId: 'prod_space_pod_x7',
              productSku: 'WCH-POD-X7',
              productName: { en: 'Space Capsule Luxury Glamping Pod X7', zh: '太空舱豪华露营胶囊 X7' },
              selectedOptions: [],
              calculatedPriceUsd: { amountCents: Math.round(61200 * 100), currency: 'USD' },
              calculatedWeightKg: 9130,
              calculatedCbm: 122.2,
              calculatedLeadTimeDays: 43,
              containersRequired: 1,
              createdAt: '2025-01-12T09:15:00Z',
            },
            quantity: 12,
            unitPriceUsd: { amountCents: Math.round(59800 * 100), currency: 'USD' },
            totalPriceUsd: { amountCents: Math.round(717600 * 100), currency: 'USD' },
            leadTimeDays: 40,
          },
        ],
        subtotalUsd: { amountCents: Math.round(717600 * 100), currency: 'USD' },
        seaFreightEstimateUsd: { amountCents: Math.round(48000 * 100), currency: 'USD' },
        customsInsuranceEstimateUsd: { amountCents: Math.round(14200 * 100), currency: 'USD' },
        discountUsd: { amountCents: Math.round(16800 * 100), currency: 'USD' },
        totalUsd: { amountCents: Math.round(763000 * 100), currency: 'USD' },
        incoterms: 'DDP',
        paymentTermsNote: '30% Deposit upon contract signing; 40% Mid-production completion; 30% Pre-shipment dispatch.',
        validityDays: 30,
      },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_2025_9912',
    orderNumber: 'ORD-2025-9912',
    quoteId: 'qte_2025_8819',
    quoteNumber: 'QTE-2025-8819',
    projectId: 'proj_big_sur_resort',
    projectName: 'Big Sur Coastline Eco Resort Phase 1',
    organizationId: 'org_horizon_resorts',
    state: 'PRODUCTION',
    stateHistory: [
      { state: 'ACCEPTED', timestamp: '2025-01-20T16:45:00Z', updatedBy: 'Alex Morgan' },
      { state: 'PRODUCTION', timestamp: '2025-02-05T09:00:00Z', updatedBy: 'Factory Chief Engineer' },
    ],
    acceptedQuoteSnapshot: MOCK_QUOTES[0].currentVersion,
    paymentMilestones: [
      {
        id: 'ms_1_deposit',
        stageName: '30% Contract Deposit',
        percentage: 30,
        amountUsd: { amountCents: Math.round(228900 * 100), currency: 'USD' },
        dueDate: '2025-01-28',
        status: 'VERIFIED_PAID',
        bankRefNumber: 'DEMO-WIRE-REFERENCE',
      },
    ],
    invoices: [
      {
        id: 'inv_1001',
        invoiceNumber: 'INV-2025-1001',
        orderId: 'ord_2025_9912',
        orderNumber: 'ORD-2025-9912',
        milestoneId: 'ms_1_deposit',
        stageTitle: '30% Contract Deposit',
        amountUsd: { amountCents: Math.round(228900 * 100), currency: 'USD' },
        currency: 'USD',
        convertedAmount: { amountCents: Math.round(228900 * 100), currency: 'USD' },
        issuedDate: '2025-01-21',
        dueDate: '2025-01-28',
        status: 'PAID',
        sellerBankDetails: {
          bankName: 'DEMO BANK, DO NOT PAY',
          swiftCode: 'DEMO-SWIFT',
          accountName: 'WUCHAN DEMO ONLY',
          accountNumber: 'REDACTED-DEMO-ACCOUNT',
          bankAddress: 'Synthetic demo data. Not a payment destination.',
        },
        paymentReceipts: [],
      },
    ],
    shipments: [
      {
        id: 'shp_9088',
        shipmentNumber: 'SHP-2025-9088',
        orderId: 'ord_2025_9912',
        orderNumber: 'ORD-2025-9912',
        shippingLine: 'COSCO SHIPPING Lines',
        vesselName: 'COSCO SHIPPING UNIVERSE',
        voyageNumber: '088E',
        billOfLadingNumber: 'COSU639201948',
        originPort: 'Port of Ningbo-Zhoushan (CNNGB)',
        destinationPort: 'Port of Los Angeles (USLAX)',
        estimatedDeparture: '2025-04-18',
        estimatedArrival: '2025-05-02',
        currentStatus: 'PACKING',
        containers: [
          {
            id: 'cntr_1',
            containerNumber: 'CSQU8921045',
            sealNumber: 'COS-SEAL-88219',
            containerType: '40ft_HC',
            totalWeightKg: 9130,
            totalCbm: 122.2,
            packages: [
              {
                id: 'pkg_1_1',
                packageCode: 'PKG-POD-001-A',
                description: 'Main Capsule Body & Steel Base Frame',
                weightKg: 6500,
                lengthMm: 11500,
                widthMm: 3300,
                heightMm: 3200,
                cbm: 95.0,
                itemsInside: ['Galvanized Chassis', 'PU Insulated Shell'],
              },
            ],
          },
        ],
        trackingEvents: [],
      },
    ],
    engineeringDrawingApproved: true,
    productionProgressPct: 62,
    responsibleAccountManager: {
      name: 'Marcus Vance',
      title: 'Senior Account Director',
      email: 'm.vance@wuchan-group.com',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    },
    responsibleFactoryEngineer: {
      name: 'Li Wei',
      title: 'Lead Modular Structural Engineer',
      email: 'w.li@wuchan-engineering.cn',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    createdAt: '2025-01-20T16:45:00Z',
    updatedAt: '2025-02-05T09:00:00Z',
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'doc_eng_001',
    title: 'X7 Pod Structural & Foundation Engineering Drawings (PE Stamped)',
    category: 'ENGINEERING_DRAWING',
    projectId: 'proj_big_sur_resort',
    orderId: 'ord_2025_9912',
    accessLevel: 'CUSTOMER_ORGANIZATION',
    currentVersion: {
      versionNumber: 2,
      fileName: 'WCH-X7-BigSur-Structural-PE-Stamped-v2.pdf',
      fileUrl: '#',
      fileSizeBytes: 18400000,
      uploadedAt: '2025-01-25T11:00:00Z',
      uploadedBy: 'Li Wei (Lead Structural Engineer)',
    },
    versionHistory: [],
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_big_sur_eng',
    topic: 'Big Sur Highway 1 Site Foundation Tie-Down Specifications',
    contextType: 'ORDER',
    contextId: 'ord_2025_9912',
    participants: [],
    unreadCount: 0,
    updatedAt: '2025-02-05T11:20:00Z',
    lastMessage: {
      id: 'msg_3',
      conversationId: 'conv_big_sur_eng',
      senderId: 'li_wei',
      senderName: 'Li Wei (WUCHAN Engineer)',
      senderRole: 'Lead Structural Engineer',
      content: 'We have updated the PE-stamped foundation anchor bolt drawing (v2).',
      createdAt: '2025-02-05T11:20:00Z',
    },
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg_1',
    conversationId: 'conv_big_sur_eng',
    senderId: 'usr_lead_1',
    senderName: 'Alex Morgan',
    senderRole: 'Procurement Lead',
    content: 'Hi Li Wei, Monterey County planning department asked for shear-wall calculations.',
    createdAt: '2025-02-04T15:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    userId: 'usr_lead_1',
    title: 'Production Update: ORD-2025-9912',
    body: 'Structural steel welding reaches 62% completion.',
    type: 'MILESTONE_UPDATED',
    linkUrl: '/orders/ord_2025_9912',
    read: false,
    createdAt: '2025-02-05T09:05:00Z',
  },
];
